package today.opai.api.enums;

public enum EnumShopItem {
    WOOL, CLAY, GLASS, END_STONE, LADDER, WOOD, OBSIDIAN,
    STONE_SWORD, IRON_SWORD, DIAMOND_SWORD, KB_STICK,
    CHAINMAIL_ARMOR, IRON_ARMOR, DIAMOND_ARMOR,
    SHEARS, WOODEN_PICKAXE, IRON_PICKAXE, GOLDEN_PICKAXE, DIAMOND_PICKAXE, WOODEN_AXE,
    ARROW, BOW, BOW_POWER_I, BOW_POWER_I_PUNCH_I,
    SPEED_POTION, JUMP_POTION, INVISIBILITY_POTION,
    GOLDEN_APPLE, BEDBUG, DREAM_DEFENDER, FIREBALL, TNT, ENDER_PEARL, WATER_BUCKET, BRIDGE_EGG, MAGIC_MILK, SPONGE, TOWER_PANE;
}
